### Задача 1.
Первые лекции позади, пора приступать к практике!

Давайте для начала напишем самый простой запрос и посмотрим, как выглядит таблица `products`.
Выведите все записи из таблицы `products`.

Поля в результирующей таблице: `product_id`, `name`, `price`

```SQL
SELECT
  product_id,
  name,
  price
FROM
  products
```

### Задача 2.
Для сортировки значений по какой-либо колонке в SQL используется оператор `ORDER BY` с ключевыми словами `ASC` (по возрастанию) или `DESC` (по убыванию).

При этом по умолчанию сортировка происходит по возрастанию, т.е. `ASC` указывать не обязательно. Для сортировки по убыванию после `ORDER BY` необходимо явно указать `DESC`

Выведите все записи из таблицы `products`, отсортировав их по наименованиям товаров в алфавитном порядке, т.е. по возрастанию. Для сортировки используйте оператор `ORDER BY`.

Поля в результирующей таблице: `product_id`, `name`, `price`

```SQL
SELECT
  product_id,
  name,
  price
FROM
  products
ORDER BY 
  name
```

### Задача 3.
Сортировать результат SQL-запроса можно сразу по нескольким колонкам, указывая их после `ORDER BY` через запятую вместе с направлением сортировки (`ASC` или `DESC`)

Отсортируйте таблицу `courier_actions` сначала по колонке `courier_id` по возрастанию `id` курьера, потом по колонке `action` (снова по возрастанию), а затем по колонке `time`, но уже по убыванию — от самого последнего действия к самому первому. Не забудьте включить в результат колонку `order_id`.

Добавьте в запрос оператор `LIMIT` и выведите только первые 1000 строк результирующей таблицы.

Поля в результирующей таблице: `courier_id`, `order_id`, `action`, `time`

```SQL
SELECT
  courier_id,
  order_id,
  action,
  time
FROM
  courier_actions
ORDER BY
  courier_id,
  action,
  time DESC
LIMIT
  1000
```

### Задача 4.

Используя операторы `SELECT`, `FROM`, `ORDER BY` и `LIMIT`, определите 5 самых дорогих товаров в таблице `products`, которые доставляет наш сервис. Выведите их наименования и цену.

Поля в результирующей таблице: `name`, `price`

```SQL
SELECT
  name,
  price
FROM
  products
ORDER BY
  price DESC
LIMIT
  5
```

### Задача 5.

Повторите запрос из предыдущего задания, но теперь колонки `name` и `price` переименуйте соответственно в `product_name` и `product_price`.

Поля в результирующей таблице: `product_name`, `product_price`

```SQL
SELECT
  name AS product_name,
  price AS product_price
FROM
  products
ORDER BY
  price DESC
LIMIT
  5
```


### Задача 6.

Используя операторы `SELECT`, `FROM`, `ORDER BY` и `LIMIT`, а также функцию `LENGTH`, определите товар с самым длинным названием в таблице `products`. Выведите его наименование, длину наименования в символах, а также цену этого товара. Колонку с длиной наименования в символах назовите `name_length`.

Поля в результирующей таблице: `name`, `name_length`, `price`

```SQL
SELECT
  name,
  LENGTH(name) AS name_length,
  price
FROM
  products
ORDER BY
  name_length DESC
LIMIT
  1
```